const express = require('express');
const path = require('path');
const morgan = require('morgan');
const cors = require('cors');
const app = express();
const api = require('./routes/api.js');

// middlewares for all the routes
// allow cors request sites
app.use(cors({ origin: 'http://localhost:8000' }));
// app.use(morgan('combined'));
app.use(express.json());
//  bring index.html generated by react
app.use(express.static(path.join(__dirname, '..', 'public')));

// todas las rutas simplificadas en este router
app.use('/v1', api);

// en la ultima version de express se entrega el index.html por default pero no esta de mas aclararlo
app.get('/*', (req, res) => {
  res.sendFile(path.join(__dirname, '..', 'public', 'index.html'));
});

module.exports = app;
