const express = require('express');
const path = require('path');
const morgan = require('morgan');
const cors = require('cors');
// routers
const planetsRouter = require('./routes/planets/planets.router.js');
const launchesRouter = require('./routes/launches/launches.router.js');

const app = express();

// middlewares for all the routes

// allow cors request sites
app.use(cors({ origin: 'http://localhost:3000' }));
app.use(morgan('combined'));

app.use(express.json());
//  bring index.html generated by react
app.use(express.static(path.join(__dirname, '..', 'public')));

// planetsRouter is an objectwith the methods like get routes
app.use('/planets', planetsRouter);
// el path que usan todas las rutas
app.use('/launches', launchesRouter);

// en la ultima version de express se entrega el index.html por default pero no esta de mas aclararlo
app.get('/*', (req, res) => {
  res.sendFile(path.join(__dirname, '..', 'public', 'index.html'));
});

module.exports = app;
